### ISSUE TITLE
is generator a mgw to .bin converter?

### ISSUE THREAD

**Issue by jsmolina** [pcornier/GnW_MiSTer#1]
Looks like it's very tighly coupled to canvas... I tried decoupling to a node.js script, but looks so hard.
Could you help us to create a tool to convert it? 

Included dkjr looks amazing!

**Comment by pcornier** [comment]
I would not spend a lot of time on this now as I started to work on some changes that make the previous format obsolete. Additionally, I plan to use the framebuffer mode at some point.

I leave it open anyway so I will remember to look at the mgw format.

**Comment by pcornier** [comment]
Closing this one as I don't plan to do anything with mgw.
